### ISSUE TITLE
zopflipng.exe Quarantined by Malewarebytes (Spyware.Ursnif)

### ISSUE THREAD

**Issue by Jakob-Maudience** [imagemin/zopflipng-bin#13]
I'm assuming this is a false positive, but just wanted to be sure.

![mbam_2018-01-22_10-18-30](https://user-images.githubusercontent.com/24442559/35231206-cb1b4998-ff5d-11e7-942a-f82f05d6ca56.png)

Using node package version 4.1.0

**Comment by XhmikosR** [comment]
That's a false positive. I built the binary myself from the source code. See https://github.com/imagemin/zopflipng-bin/issues/6#issuecomment-354095014

**Comment by XhmikosR** [comment]
@sindresorhus this can be closed

**Comment by sindresorhus** [comment]
The only malware on your machine is Malewarebytes. Anti-virus apps cause more problems than they solve.
