### ISSUE TITLE
Upgrade zopflipng-bin to use the latest zopflipng release

### ISSUE THREAD

**Issue by utatti** [imagemin/zopflipng-bin#6]
Hi,

I use [grunt-image](https://github.com/1000ch/grunt-image) which uses zopflipng-bin as its dependency. I found that for some specific PNGs, there comes error messages like below:

```
Warning: Command failed: .../node_modules/zopflipng-bin/vendor/zopflipng -y --lossy_8bit --lossy_transparent ...
Optimizing ...
Encoding error 82: color conversion to palette requested while a color isn't in palette
Decoding error 82: color conversion to palette requested while a color isn't in palette
```

I've investigated a bit and found that [it's been fixed in zopflipng](https://github.com/google/zopfli/issues/32), but zopflipng-bin is using an old version. I've replaced `zopflipng-bin/vendor/zopflipng` with the latest release manually and it worked well. I think it's good to use the latest official release.

I will upload a PR soon.

Thanks,

**Comment by noraesae** [comment]
If this can be merged, could there be a new release into NPM?

**Comment by jgstew** [comment]
It would also be useful if these binary builds were updated: https://github.com/imagemin/zopflipng-bin/tree/master/vendor

**Comment by noraesae** [comment]
Actually, I've thought it as well, but my env is limited only to macOS. I thought I would not touch them rather than update only one env.

**Comment by sindresorhus** [comment]
I've updated the macOS binary to latest master of `zopfli`, but I don't have Linux or Window nor time to do those.

// @shinnn @1000ch

**Comment by XhmikosR** [comment]
@sindresorhus @shinnn: from https://github.com/XhmikosR/zopfli

[zopflipng.zip](https://github.com/imagemin/zopflipng-bin/files/1202213/zopflipng.zip)

Built with VS2017, statically linked, LTCG etc.

**Comment by XhmikosR** [comment]
I also build jpegoptim, gifsicle, optipng for Windows with the same compiler and options so if you need those too ping me.

**Comment by sindresorhus** [comment]
I've upgraded Zopfli to the latest commit. The latest official release is ancient.

- [x] macOS binary
- [] Linux binary
- [] Windows binary

@XhmikosR Can you provide Windows binary for https://github.com/imagemin/zopflipng-bin/commit/3334184abea8178e89c249c50cbef2716dc529c6 ?

**Comment by XhmikosR** [comment]
@sindresorhus: here you go.

[zopflipng-1.0.1-41-g84d94a4-win64-msvc-2017-static-ltcg.zip](https://github.com/imagemin/zopflipng-bin/files/1588910/zopflipng-1.0.1-41-g84d94a4-win64-msvc-2017-static-ltcg.zip)

The git describe tag refers to my own fork's hash.

**Comment by sindresorhus** [comment]
@XhmikosR Thanks :)

**Comment by XhmikosR** [comment]
@sindresorhus this can be closed. I will provide a binary for 1.0.2 in a PR.

**Comment by jgstew** [comment]
Thanks! Now I forget what I was trying to use this for.
